name: parallel
on:
  push:
    branches:
jobs:
  parallel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "action test12783612798637821963782167389126" >test.txt
      - uses: actions/upload-artifact@v3
        with:
          name: parallel_test
          path: test.txt
  test1:
    needs: [ parallel ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: parallel_test
      - run: ls
      - run: cat test.txt
  test2:
    needs: [ parallel ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: parallel_test
      - run: ls
      - run: cat test.txt
