name: postman

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  postman_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install postman-to-openapi
        run: yarn add postman-to-openapi

      - name: Convert postman collection to openapi
        uses: actions/github-script@v6
        with:
          script: |
            const postmanToOpenApi = require("postman-to-openapi");           

            const postmanCollection = "./POLARISHARE_APIS.postman_collection.json";
            const outputFile = "./collection.yml";

            postmanToOpenApi(postmanCollection, outputFile, { defaultTag: "General" })
              .then((result) => { console.error('done') })
              .catch((err) => { console.error(err) });

      - name: Validate openapi
        run: cat ./collection.yml
