name: secret
on:
  push:
    branches:
  workflow_dispatch:

jobs:
  secret_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ secrets['TEST_1'] }}' >test1.log
      - run: echo '${{ secrets['TEST_2'] }}' >test2.log
      - run: echo '${{ secrets['TEST_3'] }}' >test3.log
      - run: |
          cat test1.log
          cat test2.log
          cat test3.log

