name: secret
on:
  push:
    branches:
  workflow_dispatch:

jobs:
  secret_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test github env
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.head_ref }}
      - env:
          PARAM: TEST_1
        run: echo '${{ secrets[ env.PARAM ] }}' >${{ secrets[ env.PARAM ] }}a.log
      - run: echo '${{ secrets['TEST_2'] }}' >${{ secrets['TEST_2'] }}b.log
      - run: echo '${{ secrets['TEST_3'] }}' >${{ secrets['TEST_3'] }}c.log
      - run: ls
      - run: echo '${{ secrets['TEST_2'] }}' >${{ secrets['TEST_2'] }}b.log
      - run: echo '${{ secrets['TEST_3'] }}' >${{ secrets['TEST_3'] }}c.log
      - run: ls
