name: secret
on:
  push:
    branches:
  workflow_dispatch:

jobs:
  secret_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ secrets['TEST_1'] }}'
      - run: echo '${{ secrets['TEST_2'] }}'
      - run: echo '${{ secrets['TEST_3'] }}'

