on:
  pull_request:
  push:
  release:
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: send telegram message on push
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.event_name }} created from ${{ github.actor }}
            
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: send telegram message on pull_request
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ## [${{ github.base_ref }} <- ${{ github.head_ref }}] ${{ github.event_name }} created from ${{ github.actor }}
            
            PR title: ${{ github.event.pull_request.title }}
            
            Repository: ${{ github.repository }}
            
            See changes: ${{ github.event.pull_request.url }}