on:
  pull_request:
    types: [opened, review_requested]
  push:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: print event
        env:
          TEST_PRINT: ${{ toJson(github.event) }}
        run: echo "$TEST_PRINT"

      - name: print context
        env:
          TEST_PRINT: ${{ toJson(github) }}
        run: echo "$TEST_PRINT"

      - name: Check Env
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`context: ${JSON.stringify(context, null, 4)}`);

      - name: Set Env
        uses: actions/github-script@v6
        with:
          script: |
            const eventName = context.eventName
            let deployStage  = ''
            let imageTag = ''

            switch (eventName) {
              case 'push':
                deployStage = '${{ github.ref_name }}'
                imageTag = context.sha
                break;
              case 'pull_request':
                const headRef = context.payload.pull_request.head.ref
                deployStage = headRef.startsWith('seo') || headRef.startsWith('ci') ? 'dev' : ''
                imageTag = context.sha
                break;
              case 'release':
                deployStage = context.payload.release.target_commitish
                imageTag = context.payload.release.tag_name
                break;
            }
            console.log(1)
            if (deployStage && imageTag) {
              core.exportVariable('DEPLOY_STAGE', deployStage);
              core.exportVariable('IMAGE_TAG', imageTag);
            }else{
              core.setFailed(`Can't set DEPLOY_STAGE`);
              core.setFailed(`Can't set IMAGE_TAG`);
            }

      - name: test
        run: echo ${{ env.DEPLOY_STAGE }}
