name: master
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get env
        run: |
          source src/.env.development
          yarn version --new-version $PWA_VER --no-commit-hooks --no-git-tag-version

      - name: check
        run: cat package.json
